### PR TITLE
basic layout of home page

### PR DESCRIPTION
**Pull request by Dipanjana25**

### CODE REVIEW

**Comment by moinak878** [comment]
dont change the bg colour in the main css file. Thats affecting all the pages. instead make a different css file for home and make changes there or use inline styles in the Home component.

**Comment by moinak878** [comment]
@sujal3011 work on the mobile view for homepage. Desktop view will have animations and transitions while mobile view would be simple ( refer to current website )

**Comment by moinak878** [comment]
merging the PR for now.

**Comment by sujal3011** [comment]
@moinak878 ok working on it.

**Pull request merged**
